重构。
FaceXDPlus/FaceXD_SDK pull request #1
Opened 2020-04-29 15:29 UTC by phields

2020-04-29 17:51 UTC, CmST0us commented on FaceXD_WS.cs
> +            while (!stream.DataAvailable) ;
这里可能会有性能问题哦，如果当前网络流没有数据的话，会跑外占用cpu

2020-04-29 18:35 UTC, phields commented on FaceXD_WS.cs
> +            while (!stream.DataAvailable) ;
1.ws是持久性链接(https://zh.wikipedia.org/wiki/WebSocket)。
2.未连接时AcceptTcpClientAsync会阻塞进入循环。

2020-04-30 01:05 UTC, CmST0us requested changes

2020-04-30 01:05 UTC, CmST0us commented on FaceXD_WS.cs
> +            while (client.Available < 3) ;//明明是我先来的
和上面一样小于3有性能问题

2020-04-30 01:05 UTC, CmST0us commented on FaceXD_WS.cs
> +                bool fin = (bytes[0] & 0b10000000) != 0,
说明一下我们引入websocket的原因是不想自己做流的拆包。ws正好可以解决这个问题，其次是可以在日后支持不同的业务。
这里hardcode了websocket我觉得虽然现阶段能解决问题，但是后期业务扩展之后，肯定满足不了需求的

2020-04-30 01:05 UTC, CmST0us commented on FaceXD_WS.cs
> +                    // 我不是很清楚字节顺序，请编辑一下这个
网络字节序，为大端序，这里需要将网络字节序转为主机字节序

2020-04-30 01:05 UTC, CmST0us commented on FaceXD_WS.cs
> +                if (msglen == 0)
没有判断剩余buffer是否大于msglen

2020-04-30 01:05 UTC, CmST0us commented on FaceXD_WS.cs
> +            while (!stream.DataAvailable) ;
我觉得你没有明白我说的网络流没有数据。
首先ws是持久性连接，是的，所以我们需要在accept之后不断对输入的数据做处理。
但是也因为他是持续连接，建立的流中会存在某个时间没有数据的情况。
这时候DataAvailable为0，进入死循环

2020-05-02 16:07 UTC, closed without merging

2020-05-02 16:07 UTC, CmST0us commented
已由 #3 PR 处理